### PR TITLE
use wrappedJSObject wrapper for firefox

### PR DESCRIPTION
**Pull request by hmx789**
Currently, when we go to open the document in an extension, Firefox will throw an error saying: 
`DOMException: "The operation is insecure."`

Firefox wants us to use the wrappedJSObject to access this property from content script. 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts

### CODE REVIEW

**Comment by CharlyCst** [comment]
I ran into the exact same issue and this PR fixed it too, it may be worth considering merging it if Firefox extensions are a supported use case.

**Comment by ryanseddon** [comment]
Latest major release no longer uses doc.write can you test v5 and see if this works in firefox extensions now?

**Comment by hmx789** [comment]
hey @ryanseddon , I just added v5....and it works!

Thank you!

**Comment by hmx789** [comment]
Closing pull request because new version accommodates for Firefox extension

**Pull request closed without merging**
