### PR TITLE
Forward iframe ref and use React.createRef

### LINKED ISSUE #151: Forward ref
It would be nice if the `Frame` component forwarded refs so that one could access the ref by doing `<Frame ref....>`

### LINKED ISSUE #158: Upgrade to use React.createRef()
When running tests, we are getting:

`TypeError: Cannot read property 'addEventListener' of null`

which refers to this block in Frame.jsx:

```
componentDidMount() {
    this._isMounted = true;

    const doc = this.getDoc();
    if (doc && doc.readyState === 'complete') {
      this.forceUpdate();
    } else {
      this.node.addEventListener('load', this.handleLoad);
    }
  }
```

and suggests that `node` is null. We are using React >16.3, in which refs were changed to use `React.createRef()` - could this be the issue(?)

This started occurring after upgrading from v2.0.2 to v4.1.1 of `react-frame-component`.

### PR DESCRIPTION
**Pull request by walaszczykm**
This PR resolves #151 and potentially fixes #158.

Allow to pass `ref` prop to `Frame` component which will allow to reach the inner `iframe` `HTMLIFrameElement`.
The ref forwarding is done by `React.forwardRef` helper which wraps the original `Frame` class component instance. 

Additionally as mentioned in the issue #158  description it would be nice to use `React.createRef` instance for handling `<iframe />`  instance reference.

Example usage:
```ts
function Foo() {
  const iframeRef = React.useRef()

  React.useEffect(() => {
    iframe.style.setProperty('background-color', 'pink');
  }, [])

  <Frame ref={iframeRef} />
}
```

### CODE REVIEW

**Comment by walaszczykm** [comment]
@ryanseddon Sorry for not spotting the lint error earlier. The output from GitHub workflow build actions says:
```
/home/runner/work/react-frame-component/react-frame-component/src/index.js
Error:   1:8  error  Using exported name 'Frame' as identifier for default export  import/no-named-as-default
```

This refers to the line:
https://github.com/ryanseddon/react-frame-component/blob/162e5dfe74f37e68836cc773a6faf5615e759170/src/index.js#L1

Basically, it looks like lint rules have changed since the `index.js` file was touched last time or something similar 😅 
To stick with the `import/no-named-as-default` rule I have adjusted it to directly reexport the `default` from `'./Frame'`

```js
export { default } from './Frame';
```

commit: https://github.com/ryanseddon/react-frame-component/pull/189/commits/5cd7449ea39512805517d0868d54b9b4cf41ce79

**Comment by ryanseddon** [comment]
Can you also add some information to the readme about using refs too.

**Comment by walaszczykm** [comment]
> Can you also add some information to the readme about using refs too.

Sure, added here: https://github.com/ryanseddon/react-frame-component/pull/189/commits/0dd0bcd7bdeb406bd00282bbb186243b7b12a606 👍

**Review by ryanseddon — APPROVED** [review]
Thanks again for contributing!

**Comment by pranas** [comment]
@ryanseddon could you push a release with this? The repo is not set up to be pulled from git by npm.

**Comment by ryanseddon** [comment]
Done [v5.2.0](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.2.0)

**Comment by pranas** [comment]
Thanks for releasing it, @ryanseddon! I got iframe resizing to work by using the ref. 

I have an off-topic question: is there any way to run code in the iframe context? I noticed even UseEffect hooks are being executed on the parent page but I'm trying to get Font Face Observer to work which references `document` directly in its code.

**Comment by ryanseddon** [comment]
@pranas might be good to move that question to discussions https://github.com/ryanseddon/react-frame-component/discussions

**Comment by pranas** [comment]
Sure, posted https://github.com/ryanseddon/react-frame-component/discussions/202

**Pull request merged**
