### PR TITLE
Export context instance to allow access via static contextType property

### PR DESCRIPTION
**Pull request by dominiczaq**
Hi,

As suggested by @berdyshev here #126 I've exported context instance as default export and added test for that.

Initially I believed that this should be major version bump but as @berdyshev stated (https://github.com/ryanseddon/react-frame-component/issues/126#issuecomment-439370089) this change only adds export and do not break anything for users below react 16.6.

Edit: Changed default export to named export to allow for easy importing from library. Bumped react and react-dom in devDependancies to 16.6 to allow test to pass

### CODE REVIEW

**Comment by dominiczaq** [comment]
On the other hand without bumping react to 16.6 in peerDependancies the tests would fail.

**Comment by berdyshev** [comment]
Thank you @dominiczaq 

I think you should update exports in the `src/index.js` too to provide the context instance out of the package.

**Comment by dominiczaq** [comment]
Again @berdyshev you're right.

After checking travis I realised that tests were not failing because of peerDependancies but devDependancies - it was installing react 16.4 when running tests.

**Comment by ryanseddon** [comment]
So if someone is on 16.4.0 will this pr break for them?

**Comment by dominiczaq** [comment]
Not at all.
React 16.4 do not have contextType so the users of the package wouldn't be
able to use it it that particular way. But the old exports stayed the same.

**Pull request merged**
