### PR TITLE
Update to React 0.13.3 and ES6 class syntax

### PR DESCRIPTION
**Pull request by tanertopal**
First: Thank you very much for the work!
Second: Just in case an update of the component to React 0.13.3 with ES6 of interest for you creating a pull request.

### CODE REVIEW

**Comment by ryanseddon** [comment]
I think we'd need to clarify in the docs that the import syntax would need to be used with a module bundler. I like how react-router [document it](https://github.com/rackt/react-router#installation), perhaps borrow from them.

**Comment by tanertopal** [comment]
Updated README.md hope thats what you meant

**Comment by nelix** [comment]
Perhaps a build step to publish the module to /lib or something would be better?

**Comment by tanertopal** [comment]
Added a build step.

- original index.js is now in /src
- transpiled version in /lib

**Comment by ryanseddon** [comment]
Closing as this is quite out of date, please create another PR if you're keen to do this still.

**Pull request closed without merging**
