### PR TITLE
Add deploy script

### PR DESCRIPTION
**Pull request by hfter789**
#95 
Added deploy script to allow updating Github page with just one command.
This is what it looks like when you run
`npm run deploy`
https://hfter789.github.io/react-frame-component/
We can also do postpublish deploy so you can even save that one step!

**Note:**  The Github page is building the examples you have in master instead of the original one you have. We can either keep one example + webpack for both development and Github Page. Or we can separate into two examples + shared webpack. I personally prefer the first way because it is easier to manage, but it is up to you.

### CODE REVIEW

**Comment by ryanseddon** [comment]
Let's change the example in master to match what's in gh-pages since it's a bit more informative than the simple example we have

**Comment by ryanseddon** [comment]
> We can also do postpublish deploy 

That would be great to have can you add that to this PR too

**Comment by hfter789** [comment]
@ryanseddon  done. I couldn't test the publish step. but everything else is tested.

**Comment by ryanseddon** [comment]
oops forgot to run yarn so the yarn.lock file would be committed too

**Comment by ryanseddon** [comment]
Ok merged and published I had to clear my browser cache to make the new gh-pages branch render if you've previously visited it.

**Pull request merged**
