### PR TITLE
Add support for setting initial content of the frame,  fixes #15

### LINKED ISSUE #15: Head prop does not properly support script tags
Scripts tags inside an iframe must be created with that iframe's document createElement method. It will render the tag but the browser will ignore loading the source code.

### PR DESCRIPTION
**Pull request by ibash**
This introduces a new prop "initialContent". initialContent is injected into the
frame the first time it is rendered. That allows you to insert script tags or
whatever else into the head element. This does not attempt to update the frame
when the initialContent prop changes (hence the prop starts with "initial").

### CODE REVIEW

**Comment by ryanseddon** [comment]
Neat can you also update the readme to add the new prop with some info.

**Comment by ibash** [comment]
:+1:

**Comment by ryanseddon** [comment]
Can you rebase master with your other PR and I'll merge and cut a new release.

**Comment by ibash** [comment]
Done -- thanks for the release bump!

**Comment by ali** [comment]
This is great. Used it to add `<!DOCTYPE html>` to the top of my iframe's DOM, fixing a bug in my app.

**Comment by ibash** [comment]
@ryanseddon I just made a change that turns `firstChild` into `children[0]`. The reason why is that `node.children` does not include text nodes, while firstChild does. Although it's a minor detail, it means that you can use whitespace within `initialContent`.

**Comment by ryanseddon** [comment]
oh nice catch on the textNode thing.

**Comment by ryanseddon** [comment]
published to npm as v0.5.0, @ibash added you as a collaborator as those two PRs were awesome.

**Comment by ibash** [comment]
:+1:

**Comment by ericclemmons** [comment]
Thanks for this PR @ibash!  The lack of `<!DOCTYPE html>` actually triggers tons of quirksmode issues for us (making React think it's on IE8 O_o), but this PR was already in progress.

Good call on making him a collaborator @ryanseddon!  Excellent work.

**Comment by ibash** [comment]
Made a PR to add `<!DOCTYPE html>` as default initial content, thanks for the headsup @ali and @ericclemmons

**Pull request merged**
