### PR TITLE
chore: add declare module

### PR DESCRIPTION
**Pull request by LuizAsFight**
just adding some typescript compatibility

### CODE REVIEW

**Comment by dieguezz** [comment]
is this change lost or ever changed?

**Comment by ryanseddon** [comment]
Not sure why it was closed, is this useful to have?

**Comment by ryanseddon** [comment]
@dieguezz and `index.ts` living in the root and not along side the `index.js` in lib/ is fine?

**Comment by dieguezz** [comment]
> @dieguezz and `index.ts` living in the root and not along side the `index.js` in lib/ is fine?

To be sincere, i think you just need a *.d.ts file declaring the module. I guess that index.ts would work as well as in the PR, but [AFAIK](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) *.d.ts should be used.

**Comment by ryanseddon** [comment]
Thanks for the context, looking at the [typescript handbook](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html#-reference-ing-a-module):

> The compiler will try to find a .ts, .tsx, and then a .d.ts 

Seems it'll look for *.d.ts last so I'll leave it as .ts

**Review by ryanseddon — APPROVED** [review]

**Comment by ryanseddon** [comment]
This has now [been published](https://github.com/ryanseddon/react-frame-component/releases/tag/v5.0.1)

**Comment by erezrokah** [comment]
Hello 👋 FYI, this breaks TypeScript builds when the `isolatedModules ` flag is enabled, see https://github.com/netlify/netlify-cms/runs/4430326543?check_suite_focus=true#step:6:54

**Comment by ryanseddon** [comment]
@erezrokah thanks! What's the fix here?

**Comment by erezrokah** [comment]
I believe the fix should be to add an empty export `export {}` to the file, based on https://stackoverflow.com/questions/56577201/why-is-isolatedmodules-error-fixed-by-any-import/56577324

I can PR it today

**Comment by erezrokah** [comment]
PR at https://github.com/ryanseddon/react-frame-component/pull/203.

**Comment by vittorio** [comment]
@ryanseddon looks like this PR broke actual definitions from DefinitelyTyped
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-frame-component/index.d.ts
Sorry but what is the purpose or this old and outdated changes if you already have actual typings, not just stub?

**Comment by ryanseddon** [comment]
Not real familiar with either of this, so what's your advice to fix this? Remove the local stub and update docs to use DefinitelyTyped? Want to do a PR to fix this @vittorio?

**Comment by erezrokah** [comment]
Sorry for the breakage! Would it make sense to port the definitions from `DefinitelyTyped` to this package?

**Comment by ryanseddon** [comment]
@erezrokah would probably make sense, DefinitelyTyped also recommends you remove the types once that is done https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by alexandretrichot** [comment]
J'ai réécrit ce module à l'aide de typescript à cause de ce problème et pour mes propres besoin. J'ai utilisé les hooks, et vitejs pour la demo. Manque les tests mais reste anecdotique pour mon usage. Vous pourez tester si vous voulez.
https://github.com/alexandretrichot/ts-react-frame-component

**Comment by vittorio** [comment]
Yeah, i can raise PR with type definitions.

**Comment by alexandretrichot** [comment]
I propose to migrate the library on typescript sources. I found some potential bugs just with type checking. I could write a PR to bring all this up to date. Tell me if you are interested. I would like to do that.
I mention it here because it will solve this problem and a few others. Tell me if I should spend some time reintegrating tests, eslint, prettier etc

**Comment by ryanseddon** [comment]
@alexandretrichot I'd be open to this. @vittorio can you collaborate on this too?

**Pull request merged**
