### PR TITLE
Replace document.write with innerHTML so initialContent injection does not break scripts

### PR DESCRIPTION
**Pull request by richtr**
Instead of using `document.write` to inject `initialContent` we can use `innerHTML` for the same purpose which does not break `<script>` injection.

### CODE REVIEW

**Comment by ryanseddon** [comment]
Does this work in all browsers? It's been a while but I'm pretty sure this doc.write stuff is needed for this to work cross browser.

**Comment by pgarciacamou** [comment]
@ryanseddon I'm having the same issue as @richtr 

I have a different proposal, #85

**Comment by ibash** [comment]
FWIW we ended up using `srcDoc` instead of `document.write`: https://github.com/superhuman/react-frame-component/pull/2/commits/a84f7d24bc5ac2949ab4de294ae2dd811cc48907

The reason why is that in electron `document.open` causes a crash in some cases.

**Comment by pgarciacamou** [comment]
@ryanseddon I was playing with `srcDoc` as mentioned by @ibash to try and created https://github.com/ryanseddon/react-frame-component/pull/124.

The main difference is that `srcDoc` will trigger an async load and I'm not sure if that is what you want or if it could possibly break current community usage of `react-frame-component` (this could be done on a _minor_ version bump).

That said, the compatibility of innerHTML is pretty good and are similar to React16's browser compatibility see: https://quirksmode.org/dom/html/ and https://reactjs.org/docs/react-dom.html#browser-support (`<IE11` partially support for both). Adding to this, Microsoft made obsolete `<IE10` since Jan 12 2016. It is safe to say that this library could drop support for `<IE10` on the next _minor_ version.

Now, if you look at the chart in the _quirksmode_ link, you will see that the issues with IE and `innerHTML` are only related to specific tags and not to the entire DOM (as it is done by @richtr in this PR), so I think this PR is good and potentially better than #124

Either way, I would advise bumping a _minor_ version to prevent any possibility of breaking `npm` dependencies that auto upgrade patches.

**Comment by pgarciacamou** [comment]
Also, the conflicts are just related to prettier.

**Comment by ryanseddon** [comment]
Thanks for the info @pgarciacamou I too think `innerHTML` is the best approach as `srcDoc` will exclude edge support too.

**Comment by richtr** [comment]
Rebased this PR to latest `master` branch just now.

**Comment by pgarciacamou** [comment]
Ok, I found one major flaw with `innerHTML` that could potentially break a bunch of apps, including the one I tested it in.

> HTML5 specifies that a <script> tag inserted with innerHTML should not execute.
> https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#Security_considerations

Basically, this works with `doc.write` and doesn't with `innerHTML`:

```js
<Frame
  initialContent={`
    <html>
      <head>
        <script>alert('I am John in an annoying alert!')</script>
      </head>
      <body>
        <h1>i wont be changed</h1>
      </body>
    </html>
  `}
/>
```

Any thoughts?

**Comment by dominiczaq** [comment]
I would say that using script tags in iframe is probably very common and
using innerHTML would severely reduce usefulness of react-frame-component.

**Comment by ryanseddon** [comment]
> Basically, this works with doc.write and doesn't with innerHTML

Hmm that's a pretty big limitation not sure if this is the right solution then.

> Also, this should work with srcDoc as I tested it with a small abstraction of #124.

My only concern is that `srcDoc` doesn't work in edge or IE wondering if we can combine both doc.write and srcDoc where available.

Can someone explain again what this pr is solving again?

I remember from yonder that jQuery hand;ed the script case using their innerHTML wrapper `$.html()` so I looked at their code and the basically extract all scripts and eval them to support it.

**Comment by pgarciacamou** [comment]
> Can someone explain again what this pr is solving again?

Honestly, I can't remember the issue I was having when I created #85 (it was too long ago). Maybe @richtr can add more details of what he meant with "_we can use innerHTML for the same purpose which does not break <script> injection_".

But I think it was related to:

> Starting in 55, Chrome will not execute <script> elements injected via document.write() in case of an HTTP cache miss for users on a 2G connection.

* https://blog.dareboost.com/en/2016/09/avoid-using-document-write-scripts-injection/
* https://developers.google.com/web/updates/2016/08/removing-document-write

The last link makes me lean strongly towards `srcDoc` being the best approach.

Also, removing `doc.write` removes the Chrome warning: `[Violation] Avoid using document.write`.

---------

> I would say that using script tags in iframe is probably very common and
using innerHTML would severely reduce usefulness of react-frame-component.

Agreed.

> My only concern is that `srcDoc` doesn't work in edge or IE wondering if we can combine both doc.write and srcDoc where available.

You are correct (https://caniuse.com/#feat=iframe-srcdoc) I didn't know this. **I think this is the best approach as it would be backward compatible and it would act as a fall back only.**

My only concern is that this would most likely require a major version bump because of the asynchronous loading.

**Comment by pgarciacamou** [comment]
I can give it a try as soon as I have time, stay tuned.

> I'm fine with a major bump what's your concern with this?

I guess I'm just being straightforward because it is your library after all and I want to make sure I'm not pushing in the opposite direction of what you have in mind.

**Comment by Kwon11** [comment]
I'd appreciate it if yall had the time to merge this. It looks like it all checks out and is even compatible with the recent versions of IE and it got stuck because the owner wanted to give some thought to bumping the version number.

I can go off of @richtr 's branch. I have confirmed that it works.

If the owner @ryanseddon has no other problems with it I will rebase Richtr's work and submit a PR to his branch to submit to this branch? Not sure how that workflow would work.

My use case: I need to have a script tag in the <head> in order to have axe-core recognize my iframe and analyze it for accessibility issues.

**Comment by ryanseddon** [comment]
@Kwon11 I justed merged master to keep this PR fresh so we can move this one into it. I'm just gonna do some manual testing before merging

**Comment by ryanseddon** [comment]
@Kwon11 just confirming how does this fix your usecase? innerhtml doesn't execute scripts?

**Comment by Kwon11** [comment]
@ryanseddon thank you for responding so quickly. I see that the carrot tags removed my "head" statement.

It fixes my use case because axe core requires that script in the head, and that currently breaks react-frame-component (uncaught typeerror: cannot read property children of null). 

Putting the script in the body or outside the body will not work. It must be head apparently.

**Comment by ryanseddon** [comment]
@Kwon11 
> It fixes my use case because axe core requires that script in the head

If this is the case then it should already work in the current master? Nothing about this PR will change how the `head` prop currently works. Can you create a codesandbox.io?

**Comment by Kwon11** [comment]
oh man. I've been using `initialContent` with 

`<!DOCTYPE html><html><head><script type="text/javascript" src="node_modules/axe-core/axe.min.js" ></script></head><body><div></div></body></html>`

I can probably just insert it into head.

**Comment by Kwon11** [comment]
I am having issues with getting the scripts to run in the HEAD. It may be from parcel, or react frame component, or from HTML2React. I am currently trying to debug this.

Using initialContent, the script does not show up in the head. I am on 4.1.0. Richtr's branch gets me up and running (though it may just be a workaround for an issue in a different package). If you intend to merge Richtr's branch anyway, it'd help me out. Otherwise I shall bear my cross and march forward. My company has a long process for self-hosting our packages.

**Comment by ryanseddon** [comment]
React will never execute scripts rendered in JSX otherwise on every render of that component it'd reload that script.

What you need to do is create a useEffect to run on mount or componentDidMount for a class component.

Something like this https://codesandbox.io/s/reverent-almeida-lkx14

**Comment by entiendoNull** [comment]
Sorry for reopening this issue, but I am confused of what this discussion resulted in. I am using the latest version (4.1.1) of this component and when having script tags in my `initialContent` my app breaks badly.

Skärmavbild 2019-09-24 kl  08 58 58

As soon as I remove script tags this error is gone. In the `react-frame-component` source the following changes that were committed are not to be found (and if I manually make that change, it still breaks):
```
doc.documentElement.innerHTML = this.props.initialContent;
this._setInitialContent = true;
```

Was this issue ever resolved? Or if my initialContent, e.g. includes script src to jQuery should I use something similar to what @ryanseddon suggests here: https://github.com/ryanseddon/react-frame-component/pull/80#issuecomment-502897381

**Pull request closed without merging**
